name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup testing environment
        uses: codecrafters-io/dns-server-tester/.github/actions/setup@main

      - run: make test
